spring:
  application:
    name: provider-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: provider-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:postgresql://localhost:5432/provider_db
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  port: 8081

provider:
  kafka:
    topic: payment-requests
    results-topic: provider-events

outbox:
  relay:
    instance-id: ${HOSTNAME:default-instance}
    fixed-delay-ms: 200
    batch-size: 10
    stale-claim-after-ms: 30000
